/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e8ddff",
        "tertiary": "#30007f",
        "tertiary-container": "#471ba5",
        "primary-fixed-dim": "#bfc2ff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c5d4",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#2addcd",
        "on-error-container": "#93000a",
        "surface-tint": "#4f54b1",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#57fae9",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#363b98",
        "primary-container": "#2d328f",
        "on-tertiary-fixed-variant": "#5028ae",
        "surface-container-lowest": "#ffffff",
        "outline": "#767683",
        "primary-fixed": "#e0e0ff",
        "on-tertiary-fixed": "#21005e",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#b39aff",
        "on-secondary-fixed": "#00201d",
        "on-secondary-container": "#007168",
        "error": "#ba1a1a",
        "primary": "#141779",
        "on-surface-variant": "#464652",
        "inverse-primary": "#bfc2ff",
        "on-primary-fixed": "#01006e",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#cebdff",
        "on-primary-container": "#9ba1ff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "secondary": "#006a62",
        "surface-container": "#eceef0",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#005049",
        "secondary-fixed": "#57fae9",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "on-error": "#ffffff",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "sans": ["Quicksand", "sans-serif"],
        "headline": ["Quicksand"],
        "display": ["Quicksand"],
        "body": ["Quicksand"],
        "label": ["Quicksand"]
      }
    },
  },
  plugins: [],
}
