#!/usr/bin/env node
/**
 * Generates tool-specific copies of the AI rules and skills kept in `.agents/`.
 *
 *   .agents/rules/*.md          → .cursor/rules/*.mdc               (Cursor)
 *                               → .github/instructions/*.instructions.md (GitHub Copilot)
 *                               → .claude/rules/*.md                 (Claude Code)
 *   .agents/skills/<name>/      → .claude/skills/<name>/             (Claude Code)
 *
 * Antigravity reads `.agents/rules/` and `.agents/skills/` directly; Cursor and Copilot read
 * `.agents/skills/` directly. Only the copies above need generating.
 *
 * Usage:
 *   node .agents/sync.mjs           write the generated files
 *   node .agents/sync.mjs --check   exit 1 if any generated file is missing or stale (CI / pre-commit)
 *
 * Generated files carry GENERATED_MARKER. Files without it are hand-written and never touched.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const isCheckOnly = process.argv.includes('--check');

const RULES_SOURCE = '.agents/rules';
const SKILLS_SOURCE = '.agents/skills';
const GENERATED_MARKER = 'GENERATED by .agents/sync.mjs';
const MARKER_COMMENT = `<!-- ${GENERATED_MARKER} from {source}. Edit the source, then run: node .agents/sync.mjs -->`;

const TRIGGERS = Object.freeze({
  ALWAYS_ON: 'always_on',
  GLOB: 'glob',
  MODEL_DECISION: 'model_decision',
  MANUAL: 'manual',
});

const RULE_TARGETS = Object.freeze({
  CURSOR: '.cursor/rules',
  COPILOT: '.github/instructions',
  CLAUDE: '.claude/rules',
});
const SKILL_TARGET = '.claude/skills';

const toPosix = (filePath) => filePath.split(path.sep).join('/');
const absolute = (relativePath) => path.join(repoRoot, relativePath);
const normalizeNewlines = (text) => text.replace(/\r\n/g, '\n');

const parseFrontmatter = (text, sourcePath) => {
  const match = normalizeNewlines(text).match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);

  if (!match) {
    throw new Error(`${sourcePath}: missing YAML frontmatter`);
  }

  const fields = {};

  for (const line of match[1].split('\n')) {
    const fieldMatch = line.match(/^([A-Za-z_-]+):\s*(.*)$/);

    if (fieldMatch) {
      fields[fieldMatch[1]] = fieldMatch[2].trim().replace(/^(['"])(.*)\1$/, '$2');
    }
  }

  return { fields, frontmatter: match[1], body: match[2].replace(/^\n+/, '') };
};

const quoteYaml = (value) => `'${String(value).replace(/'/g, "''")}'`;

const splitGlobs = (globs = '') =>
  globs
    .split(',')
    .map((glob) => glob.trim())
    .filter(Boolean);

const markerFor = (source) => MARKER_COMMENT.replace('{source}', source);

const buildCursorRule = ({ fields, body }, source) => {
  const lines = ['---', `description: ${quoteYaml(fields.description || '')}`];

  if (fields.trigger === TRIGGERS.GLOB) {
    lines.push(`globs: ${splitGlobs(fields.globs).join(',')}`);
  }

  lines.push(`alwaysApply: ${fields.trigger === TRIGGERS.ALWAYS_ON}`, '---', markerFor(source), '', body);

  return lines.join('\n');
};

const buildCopilotInstruction = ({ fields, body }, source) => {
  const lines = ['---', `description: ${quoteYaml(fields.description || '')}`];

  if (fields.trigger === TRIGGERS.ALWAYS_ON) {
    lines.push(`applyTo: '**'`);
  }

  if (fields.trigger === TRIGGERS.GLOB) {
    lines.push(`applyTo: ${quoteYaml(splitGlobs(fields.globs).join(','))}`);
  }

  lines.push('---', markerFor(source), '', body);

  return lines.join('\n');
};

// Claude Code loads `.claude/rules/*.md` without `paths` on every request, so only always-on and
// glob rules are generated. Model-decision rules are listed in AGENTS.md and read on demand.
const buildClaudeRule = ({ fields, body }, source) => {
  if (fields.trigger === TRIGGERS.ALWAYS_ON) {
    return [markerFor(source), '', body].join('\n');
  }

  if (fields.trigger === TRIGGERS.GLOB) {
    const pathLines = splitGlobs(fields.globs).map((glob) => `  - ${quoteYaml(glob)}`);

    return ['---', 'paths:', ...pathLines, '---', markerFor(source), '', body].join('\n');
  }

  return null;
};

const buildSkillFile = (text, source) => {
  const { frontmatter, body } = parseFrontmatter(text, source);

  return ['---', frontmatter, '---', markerFor(source), '', body].join('\n');
};

const listFiles = (relativeDirectory) => {
  const directory = absolute(relativeDirectory);

  if (!fs.existsSync(directory)) {
    return [];
  }

  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const relativePath = toPosix(path.join(relativeDirectory, entry.name));

    return entry.isDirectory() ? listFiles(relativePath) : [relativePath];
  });
};

const isGenerated = (relativePath) =>
  fs.existsSync(absolute(relativePath)) &&
  fs.readFileSync(absolute(relativePath), 'utf8').includes(GENERATED_MARKER);

const collectExpectedFiles = () => {
  const expected = new Map();

  const ruleSources = listFiles(RULES_SOURCE).filter((file) => file.endsWith('.md'));

  for (const source of ruleSources) {
    const parsed = parseFrontmatter(fs.readFileSync(absolute(source), 'utf8'), source);
    const name = path.basename(source, '.md');

    if (!Object.values(TRIGGERS).includes(parsed.fields.trigger)) {
      throw new Error(`${source}: trigger must be one of ${Object.values(TRIGGERS).join(', ')}`);
    }

    expected.set(`${RULE_TARGETS.CURSOR}/${name}.mdc`, buildCursorRule(parsed, source));
    expected.set(`${RULE_TARGETS.COPILOT}/${name}.instructions.md`, buildCopilotInstruction(parsed, source));

    const claudeRule = buildClaudeRule(parsed, source);

    if (claudeRule) {
      expected.set(`${RULE_TARGETS.CLAUDE}/${name}.md`, claudeRule);
    }
  }

  for (const source of listFiles(SKILLS_SOURCE)) {
    const target = `${SKILL_TARGET}/${source.slice(SKILLS_SOURCE.length + 1)}`;
    const text = fs.readFileSync(absolute(source), 'utf8');

    expected.set(target, source.endsWith('/SKILL.md') ? buildSkillFile(text, source) : normalizeNewlines(text));
  }

  return expected;
};

// A generated skill's supporting files carry no marker; they belong to the skill folder whose
// SKILL.md does.
const isInGeneratedSkill = (relativePath) => {
  const [skillName] = relativePath.slice(SKILL_TARGET.length + 1).split('/');

  return isGenerated(`${SKILL_TARGET}/${skillName}/SKILL.md`);
};

const findStaleFiles = (expected) => {
  const ruleOutputs = Object.values(RULE_TARGETS).flatMap(listFiles).filter(isGenerated);
  const skillOutputs = listFiles(SKILL_TARGET).filter(isInGeneratedSkill);

  return [...ruleOutputs, ...skillOutputs].filter((file) => !expected.has(file));
};

// Stops at the target roots, so `.claude/skills` itself is never removed.
const removeEmptyParents = (relativeDirectory) => {
  const targetRoots = [...Object.values(RULE_TARGETS), SKILL_TARGET];
  let directory = relativeDirectory;

  while (!targetRoots.includes(directory) && fs.existsSync(absolute(directory))) {
    if (fs.readdirSync(absolute(directory)).length > 0) {
      return;
    }

    fs.rmdirSync(absolute(directory));
    directory = toPosix(path.dirname(directory));
  }
};

const run = () => {
  const expected = collectExpectedFiles();
  const problems = [];
  let writtenCount = 0;

  for (const [target, content] of expected) {
    const targetPath = absolute(target);
    const exists = fs.existsSync(targetPath);
    const isSkillSupportFile = target.startsWith(SKILL_TARGET) && !target.endsWith('/SKILL.md');

    if (exists && !isSkillSupportFile && !isGenerated(target)) {
      problems.push(`skipped ${target}: hand-written file exists (move it into .agents/ or delete it)`);
      continue;
    }

    if (exists && normalizeNewlines(fs.readFileSync(targetPath, 'utf8')) === content) {
      continue;
    }

    if (isCheckOnly) {
      problems.push(`stale ${target}`);
      continue;
    }

    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.writeFileSync(targetPath, content);
    writtenCount += 1;
  }

  for (const staleFile of findStaleFiles(expected)) {
    if (isCheckOnly) {
      problems.push(`orphaned ${staleFile}`);
      continue;
    }

    fs.rmSync(absolute(staleFile));
    removeEmptyParents(path.dirname(staleFile));
    writtenCount += 1;
  }

  problems.forEach((problem) => console.error(problem));

  if (isCheckOnly) {
    console.log(problems.length ? 'AI rule copies are out of date. Run: node .agents/sync.mjs' : 'AI rule copies are up to date.');
    process.exit(problems.length ? 1 : 0);
  }

  console.log(`Synced ${expected.size} generated files (${writtenCount} changed).`);
};

run();
